# Thi is a comment.

# For documentation on this file, please see
# https://docs.landscape.io/configuration.html

doc-warnings: yes
test-warnings: no
strictness: high
max-line-length: 160

#uses:
#    - Django 

autodetect: yes

requirements:
    - etc/requirements.txt

pep8:
    full: true

ignore-paths:
    - docs

ignore-patterns:
    - ^example/doc_.*\.py$
    - (^|/)docs(/|$)

python-targets:
    - 2
    - 3
