version: '3.7'

# Database by SQLITE
# Config settings using src

services:
  bots34:
    volumes:
      - ./src/bots:/usr/local/lib/python3.4/site-packages/bots
    build:
      context: .
      dockerfile: ./compose/bots_py34/Dockerfile
    ports:
      - "0.0.0.0:8080:8080"
    command: python -u /usr/local/bin/bots-webserver.py
